#!/bin/bash

openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout ./ssl/api.bankcat.test.key -out ./ssl/api.bankcat.test.crt -config ./configs/api.bankcat.test.conf
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout ./ssl/bankcat.test.key -out ./ssl/bankcat.test.crt -config ./configs/bankcat.test.conf
